id: I7770D117
legacy_id: P000332
ocr_import_info:
  bdrc_scan_id: W28732
  source: bdrc
  ocr_info:
    timestamp: '2020-03-13T02:52:11'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T08:18:54.756650+00:00'
last_modified: 2022-09-02 16:35:32.896406
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W28732
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW28732
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཏེར་ཆོས། བདུད་འཇོམས་གླིང་པ།
  author: བདུད་འཇོམས་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.831097954390731
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I4621:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4621
      total_pages: 602
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I4621.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8214755461776896
    legacy_id: v006
  I4617:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4617
      total_pages: 550
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4617.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.829929568228959
    legacy_id: v002
  I4625:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4625
      total_pages: 562
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I4625.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.806254581178699
    legacy_id: v010
  I4620:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4620
      total_pages: 480
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I4620.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.7756440064131387
    legacy_id: v005
  I4633:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4633
      total_pages: 502
      volume_number: 18
      volume_pages_bdrc_intro: 2
    order: 18
    base_file: I4633.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8917448320156709
    legacy_id: v018
  I4626:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4626
      total_pages: 548
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I4626.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.7688451393448098
    legacy_id: v011
  I4619:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4619
      total_pages: 500
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I4619.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8261791964528857
    legacy_id: v004
  I4631:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4631
      total_pages: 504
      volume_number: 16
      volume_pages_bdrc_intro: 2
    order: 16
    base_file: I4631.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8057008303858377
    legacy_id: v016
  I4632:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4632
      total_pages: 630
      volume_number: 17
      volume_pages_bdrc_intro: 2
    order: 17
    base_file: I4632.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.872249709474338
    legacy_id: v017
  I4636:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4636
      total_pages: 648
      volume_number: 21
      volume_pages_bdrc_intro: 2
    order: 21
    base_file: I4636.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9144506271122879
    legacy_id: v021
  I4630:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4630
      total_pages: 532
      volume_number: 15
      volume_pages_bdrc_intro: 2
    order: 15
    base_file: I4630.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8213968597805825
    legacy_id: v015
  I4623:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4623
      total_pages: 558
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I4623.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8167276480186908
    legacy_id: v008
  I4622:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4622
      total_pages: 642
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I4622.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.7706963390229798
    legacy_id: v007
  I4627:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4627
      total_pages: 522
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I4627.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8039689491318986
    legacy_id: v012
  I4634:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4634
      total_pages: 375
      volume_number: 19
      volume_pages_bdrc_intro: 2
    order: 19
    base_file: I4634.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9024438320310487
    legacy_id: v019
  I4616:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4616
      total_pages: 652
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4616.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8362371652161017
    legacy_id: v001
  I4618:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4618
      total_pages: 628
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I4618.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8028877867452824
    legacy_id: v003
  I4624:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4624
      total_pages: 432
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I4624.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.818715410604982
    legacy_id: v009
  I4635:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4635
      total_pages: 750
      volume_number: 20
      volume_pages_bdrc_intro: 2
    order: 20
    base_file: I4635.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9014149815478385
    legacy_id: v020
  I4629:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4629
      total_pages: 476
      volume_number: 14
      volume_pages_bdrc_intro: 2
    order: 14
    base_file: I4629.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8437251704844518
    legacy_id: v014
  I4628:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4628
      total_pages: 472
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I4628.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8078193917666273
    legacy_id: v013
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
