id: I7770D117
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-13T02:58:38+00:00'
last_modified: '2022-06-15T16:33:51.043892+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28732
  title: གཏེར་ཆོས། བདུད་འཇོམས་གླིང་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    A37C:
      image_group_id: I4616
      title: ''
      total_pages: 652
      order: 1
      base_file: A37C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
